#!/bin/sh

# https://stackoverflow.com/questions/4493936/could-i-change-my-name-and-surname-in-all-previous-commits

git filter-branch --commit-filter \
'export GIT_AUTHOR_NAME="Mikhail Temkine";\
export GIT_AUTHOR_EMAIL=miktemk@gmail.com;\
export GIT_COMMITTER_NAME="Mikhail Temkine";\
export GIT_COMMITTER_EMAIL=miktemk@gmail.com;\
git commit-tree "$@"'