#!/bin/sh

# https://stackoverflow.com/questions/4493936/could-i-change-my-name-and-surname-in-all-previous-commits

git filter-branch --commit-filter \
'export GIT_AUTHOR_NAME="hgb-mtemkine";\
export GIT_AUTHOR_EMAIL=mtemkine@hellogbye.com;\
export GIT_COMMITTER_NAME="hgb-mtemkine";\
export GIT_COMMITTER_EMAIL=mtemkine@hellogbye.com;\
git commit-tree "$@"'