<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>werntrans</string>
	</array>
	<key>name</key>
	<string>miktemk Phrasi</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>comment</key>
			<string>comments after a hash</string>
			<key>match</key>
			<string>\#.*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword3</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>embedded properties AKA x=y</string>
			<key>match</key>
			<string>^(    |\t)(    |\t)(\w+\s*=\s*\w+)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>standard verbi keywords</string>
			<key>match</key>
			<string>\b(MAIN)\b</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>subtemplateCall</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>wordform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>optional subtemplate call AKA [noun](---)?</string>
			<key>match</key>
			<string>\[(.*?)\]\(([^)]*?)\)\?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>wordform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>optional subtemplate call AKA word(---)?</string>
			<key>match</key>
			<string>\$?\w+?\(([^)]*?)\)\?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>comment</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>subtemplateCall</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>optional subtemplate call AKA [noun]?</string>
			<key>match</key>
			<string>\[(.*?)\]\?</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>wordformBrackets</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>subtemplateCall</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>wordformBrackets</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>wordform</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>wordformBrackets</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>wordform specification in round brackets, before subtemplate call AKA [---](---)</string>
			<key>match</key>
			<string>(\[)(.*?)(\]\()([^)]*?)(\))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>subtemplateCall</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>subtemplate calls (in sq brackets)</string>
			<key>match</key>
			<string>\[([^]]*?)\]</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>wordformBrackets</string>
				</dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>wordformBrackets</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>wordform</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>wordform specification in round brackets, before word/var AKA word(---)</string>
			<key>match</key>
			<string>\$?(\w+)?\((.*?)\)</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>vardeclare</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>all variables AKA $X</string>
			<key>match</key>
			<string>\$\w+</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.syntax_name</string>
	<key>uuid</key>
	<string>88eb4baa-abdb-4a28-9012-804680bb7b04</string>
</dict>
</plist>
